import {useEffect,useRef,useState} from 'react';
import {createChart,LineSeries,ColorType,CrosshairMode,type IChartApi,type ISeriesApi,type Time} from 'lightweight-charts';
import type {ActivityPoint} from '../types';import type {BrokerHistory} from '../lib/brokerTypes';
import {activityValue} from '../lib/marketActivityView';import {brokerFlowPoints,brokerFlowSegments} from '../lib/brokerFlow';
export const brokerColors=['#93c5fd','#67e8f9','#c4b5fd','#ff8e9c','#fcd34d','#86efac'];
export function BrokerFlowCompareChart({histories,prices,metric,cumulative,windowSize,showPrice}:{histories:BrokerHistory[];prices:ActivityPoint[];metric:'value'|'lot';cumulative:boolean;windowSize:number;showPrice:boolean}){
 const host=useRef<HTMLDivElement>(null),api=useRef<IChartApi|null>(null);const [legend,setLegend]=useState<{date:string;values:{code:string;value:number|null;color:string}[]}>({date:'',values:[]});
 useEffect(()=>{if(!host.current)return;const chart=createChart(host.current,{autoSize:true,height:350,layout:{background:{type:ColorType.Solid,color:'transparent'},textColor:'#b8c5d6',attributionLogo:true},grid:{vertLines:{visible:false},horzLines:{color:'#33404f'}},crosshair:{mode:CrosshairMode.Normal,horzLine:{color:'#93c5fd',labelBackgroundColor:'#2c3d52'},vertLine:{color:'#8799b0',labelBackgroundColor:'#2c3d52'}},leftPriceScale:{visible:true,borderVisible:false},rightPriceScale:{visible:showPrice,borderVisible:false},timeScale:{borderVisible:false,rightOffset:3},handleScroll:{pressedMouseMove:true,mouseWheel:true,horzTouchDrag:true},handleScale:{mouseWheel:true,pinch:true}});api.current=chart;
 const plotted=histories.map((h,i)=>{const rows=windowSize>0?h.series.slice(-windowSize):h.series;const values=brokerFlowPoints(rows,metric,cumulative);const s=chart.addSeries(LineSeries,{color:brokerColors[i%6],lineWidth:2,priceScaleId:'left',priceFormat:{type:'custom',formatter:(v:number)=>activityValue(v,metric==='value'?'idr':'count'),minMove:1},lastValueVisible:false,priceLineVisible:false});const segments=brokerFlowSegments(values);s.setData((segments[0]??[]).map(p=>({time:p.date as Time,value:p.value})));segments.slice(1).forEach(segment=>{const part=chart.addSeries(LineSeries,{color:brokerColors[i%6],lineWidth:2,priceScaleId:'left',priceFormat:{type:'custom',formatter:(v:number)=>activityValue(v,metric==='value'?'idr':'count'),minMove:1},lastValueVisible:false,priceLineVisible:false});part.setData(segment.map(p=>({time:p.date as Time,value:p.value})));});return {series:s,values,code:h.broker_code,color:brokerColors[i%6]};});
 const dates=plotted[0]?.values.map(p=>p.date)??[];let priceSeries:ISeriesApi<"Line">|undefined;
 if(showPrice){priceSeries=chart.addSeries(LineSeries,{color:'#f3f6fa',lineWidth:1,priceScaleId:'right',lastValueVisible:true,priceLineVisible:false});const points=prices.filter(p=>dates.includes(p.date));priceSeries.setData(points.map(p=>p.close==null?{time:p.date as Time}:{time:p.date as Time,value:p.close}));}
 const fallback={date:dates.at(-1)??'',values:plotted.map(p=>({code:p.code,color:p.color,value:p.values.at(-1)?.value??null}))};if(showPrice)fallback.values.unshift({code:'Price',color:'#f3f6fa',value:prices.find(p=>p.date===fallback.date)?.close??null});setLegend(fallback);
 chart.subscribeCrosshairMove(e=>{if(!e.time){setLegend(fallback);return;}const values=plotted.map(p=>{return {code:p.code,color:p.color,value:p.values.find(v=>v.date===String(e.time))?.value??null};});if(priceSeries){const p=e.seriesData.get(priceSeries);values.unshift({code:'Price',color:'#f3f6fa',value:p&&'value' in p?p.value:null});}setLegend({date:String(e.time),values});});chart.timeScale().fitContent();return()=>{api.current=null;chart.remove();};
 },[histories,prices,metric,cumulative,windowSize,showPrice]);
 function zoom(f:number){const s=api.current?.timeScale(),v=s?.getVisibleLogicalRange();if(s&&v){const m=(v.from+v.to)/2,h=(v.to-v.from)*f/2;s.setVisibleLogicalRange({from:m-h,to:m+h});}}
 return <section className="rf-flow-chart" aria-label="Grafik perbandingan broker"><div className="rf-chart-title"><strong>{cumulative?'Net kumulatif per segmen':'Net per sesi'} · {metric==='value'?'IDR':'Lot'}</strong><div className="ov-chart-controls"><button aria-label="Perbesar flow" onClick={()=>zoom(.65)}>+</button><button aria-label="Perkecil flow" onClick={()=>zoom(1.5)}>−</button><button onClick={()=>api.current?.timeScale().fitContent()}>Reset</button></div></div><div className="rf-crosshair" role="status"><span>{legend.date}</span>{legend.values.map(v=><span key={v.code}><i style={{background:v.color}}/>{v.code} <strong>{activityValue(v.value,v.code==='Price'||metric==='value'?'idr':'count')}</strong></span>)}</div><div ref={host} style={{height:350}}/><div className="ov-chart-foot"><span>Geser / scroll untuk jelajahi</span><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">Charts by TradingView</a></div></section>;
}
