import {Link} from "react-router-dom";
import type {PilotMethodologyPayload} from "../types";
const framework=[["S","Spot","Temukan aktivitas pasar yang tidak biasa."],["I","Investigate","Telusuri bukti yang mendukung dan melemahkan."],["G","Gauge","Nilai konsistensi bukti lintas sesi."],["N","Narrative","Susun penjelasan dari bukti yang tersedia."],["A","Assess","Pahami risiko dan ketidakpastian."],["L","Look ahead","Tentukan hal yang perlu dipantau."]];
const pages=[["Overview","Temukan investigasi menarik.","/"],["Investigations","Cari saham dan tinjau statusnya.","/investigations"],["Summary","Baca ringkasan dan bukti utama.",null],["Market activity","Telusuri harga dan aktivitas perdagangan.",null],["Broker","Lihat buyer, seller, dan perubahan aliran broker.",null],["Context","Tinjau informasi perusahaan dan konteks yang tersedia.",null],["History","Ikuti episode dan bukti dari sesi ke sesi.",null],["Watchlist","Simpan saham yang ingin dipantau.","/watchlist"]];
export function PilotMethodology({data}:{data:PilotMethodologyPayload}){
 const t=data.detector.thresholds,l=data.lifecycle.thresholds;
 return <section className="me-content"><div className="me-heading"><span className="ov-kicker">UNDERSTAND THE EVIDENCE</span><h1>Methodology</h1><p>Bagaimana SIGNAL menemukan aktivitas tidak biasa dan membangun investigasi.</p></div>
 <section className="su-panel me-framework"><div className="su-panel-head"><h2>The SIGNAL framework</h2><span>From signal to understanding</span></div><div className="me-flow">{framework.map(([letter,title,text])=><article key={letter}><span>{letter}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <div className="me-grid"><section className="su-panel"><div className="su-panel-head"><h2>Detection rules</h2><span>Hard spot</span></div><p className="me-copy">Hard spot muncul ketika compression, activity, dan metrik inti memenuhi ambang berikut bersama-sama.</p><div className="me-rules"><article><span>Compression</span><strong>≥ {t.compression}</strong><p>Harga bergerak dalam rentang yang lebih rapat terhadap baseline.</p></article><article><span>Activity</span><strong>≥ {t.activity}</strong><p>Skor aktivitas perdagangan memenuhi ambang deteksi.</p></article><article><span>Core metrics</span><strong>≥ {t.core_relative}×</strong><p>Minimal {t.core_count} metrik inti melewati ambang relatif terhadap baseline.</p></article></div><details className="me-details"><summary>Baseline &amp; histori awal</summary><p>Baseline aktivitas memakai {data.detector.metric_baseline_sessions} {data.methodology_version.includes("valid-baseline")?"observasi valid sebelumnya dalam maksimum 25 sesi perdagangan":"sesi sebelumnya"}. Baseline harga dan volume tetap mengikuti kalender asli. Kebutuhan histori awal: {data.detector.baseline_requires_preceding_sessions} sesi.</p></details></section>
 <section className="su-panel"><div className="su-panel-head"><h2>Evidence confidence</h2><span>/ 100</span></div><h3 className="me-statement">Seberapa konsisten bukti investigasinya?</h3><p className="me-copy">Confidence merangkum dukungan dan konsistensi bukti dalam investigasi. Gunakan bersama aktivitas perdagangan, persistence, dan status investigasi.</p><div className="me-callout">Skor confidence bukan probabilitas kenaikan harga atau return.</div><div className="me-terms"><div><strong>Relative activity</strong><p>Aktivitas perdagangan dibandingkan baseline historisnya.</p></div><div><strong>Persistence</strong><p>Dukungan yang bertahan selama beberapa sesi.</p></div><div><strong>Hard spot</strong><p>Sesi yang memenuhi seluruh syarat deteksi.</p></div></div></section></div>
 <section className="su-panel me-lifecycle"><div className="su-panel-head"><h2>Investigation lifecycle</h2></div><div className="me-states">{["Emerging","Developing","Established","Weakening","Closed"].map((state,i)=><div key={state}><span>0{i+1}</span><strong>{state}</strong></div>)}</div><div className="me-lifecycle-rules"><p><strong>Established</strong> memerlukan {l.established_support_count} sesi dukungan dalam {l.persistence_window} sesi dan {l.established_hard_hits} hard hit.</p><p><strong>Closed</strong> terjadi setelah {l.close_after_unsupported} sesi berturut-turut tanpa dukungan yang dapat dinilai.</p></div><details className="me-details"><summary>Bagaimana sesi yang kosong diperlakukan?</summary><p>Gap tidak dihitung sebagai sesi tanpa dukungan dan tidak otomatis menutup investigasi. Segmen diproses terpisah; status sebelum hard hit yang teramati dapat tetap belum diketahui. Data yang belum diketahui ditampilkan sebagai —.</p></details></section>
 <div className="me-grid"><section className="su-panel"><div className="su-panel-head"><h2>How to read SIGNAL</h2></div><div className="me-pages">{pages.map(([name,text,url])=><article key={name}>{url?<Link to={url}>{name} ↗</Link>:<strong>{name}</strong>}<p>{text}</p></article>)}</div></section><section className="su-panel"><div className="su-panel-head"><h2>Interpretation</h2></div><div className="me-terms"><div><strong>Harga dan bukti saling melengkapi</strong><p>Tinjau harga, aktivitas, dan aliran broker bersama-sama sebelum menarik kesimpulan.</p></div><div><strong>Broker tidak menunjukkan identitas investor</strong><p>Aliran buy/sell menggambarkan transaksi melalui broker; tidak membuktikan niat atau identitas pihak di baliknya.</p></div><div><strong>Informasi dapat belum tersedia</strong><p>Data kosong tidak dianggap sebagai nol atau bukti bahwa tidak ada aktivitas.</p></div></div><details className="me-details"><summary>Batas data &amp; rekonsiliasi</summary><ul><li>Konteks seluruh pasar dan peer belum dinilai.</li><li>Volume broker direkonsiliasi dengan data harian; cakupan pasar belum dibuktikan secara independen.</li><li>Sesi dan baseline terkait ditahan bila ada gap, nilai null, atau volume yang belum cocok.</li><li>Reaction validation lama tidak dipakai sebagai hasil analisis ini.</li></ul></details></section></div>
 <details className="su-panel me-coverage"><summary>Cakupan penilaian per saham</summary><div className="me-table-wrap"><table><thead><tr><th>Saham</th><th>Sesi</th><th>Dapat dinilai</th><th>Belum dapat dinilai</th><th>Hard spots</th></tr></thead><tbody>{Object.entries(data.detector.by_symbol).map(([symbol,s])=><tr key={symbol}><td><Link to={"/investigations/"+symbol+"/summary"}>{symbol} ↗</Link></td><td>{s.analysis_sessions}</td><td>{s.evaluated}</td><td>{s.not_evaluated}</td><td>{s.spot_hits}</td></tr>)}</tbody></table></div></details>
 </section>;
}
