import {NavbarGlass} from "../components/NavbarGlass";
import { WatchlistButton } from "../components/WatchlistButton";
import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "../lib/conceptNavigation";
import { getActivity,getInvestigations } from "../lib/api";
import type { ActivityPayload,InvestigationListItem } from "../types";
import { companyName } from "../lib/companies";
import { OverviewPriceChart } from "../components/OverviewPriceChart";
import { MarketMetricChart } from "../components/MarketMetricChart";
import { activityMetrics,activityValue,activityWindow,marketActivityView } from "../lib/marketActivityView";
import type { ActivityMetric } from "../lib/marketActivityView";
import "../overview-mockups.css";
import "../summary-mockups.css";
import "../activity-mockups.css";

const concepts=["Signal desk","Activity first","Dual lens","Compact board","Session explorer"];
const fmt=(v:number|null|undefined,d=2)=>v==null?"—":v.toLocaleString("id-ID",{maximumFractionDigits:d});
const day=(d:string)=>new Date(d+"T00:00:00").toLocaleDateString("id-ID",{day:"numeric",month:"short"});
export function ActivityMockupsPage(){
 const [params,setParams]=useSearchParams();const raw=Number(params.get("variant")??1);const variant=Number.isInteger(raw)&&raw>=1&&raw<=5?raw:1;const symbol=(params.get("symbol")??"BBCA").toUpperCase();
 const [data,setData]=useState<ActivityPayload>();const [stocks,setStocks]=useState<InvestigationListItem[]>([]);const [error,setError]=useState("");const [metric,setMetric]=useState<ActivityMetric>("turnover");const [windowSize,setWindowSize]=useState(60);const [session,setSession]=useState<string|null>(null);
 useEffect(()=>{let alive=true;getInvestigations().then(d=>alive&&setStocks(d.items)).catch(()=>{});return()=>{alive=false;};},[]);
 useEffect(()=>{let alive=true;setData(undefined);setError("");setSession(null);getActivity(symbol).then(d=>alive&&setData(d)).catch(()=>alive&&setError("Market Activity belum dapat dimuat. Pilih saham lain atau periksa server lokal."));return()=>{alive=false;};},[symbol]);
 const rows=useMemo(()=>activityWindow(data?.series??[],windowSize),[data,windowSize]);const view=useMemo(()=>marketActivityView(rows,metric),[rows,metric]);const latest=data?.series.at(-1);const focused=rows.find(p=>p.date===session)??rows.at(-1);const previous=data?.series.at(-2)?.close;const change=latest?.close!=null&&previous!=null&&previous!==0?(latest.close-previous)/previous*100:null;
 const controls=<div className="ma-toolbar"><div><span className="ma-section-label">Market activity</span><strong>Follow the activity.</strong></div><div className="ma-windows" aria-label="Periode chart">{[20,60,0].map(n=><button key={n} aria-pressed={windowSize===n} onClick={()=>{setWindowSize(n);setSession(null);}}>{n===0?"6M":`${n} sesi`}</button>)}</div></div>;
 const selector=<section className="ma-selectors" aria-label="Pilih metrik">{(Object.keys(activityMetrics) as ActivityMetric[]).map(k=>{const def=activityMetrics[k];const rawValue=latest?.[def.actual];const value=typeof rawValue==="number"?rawValue:null;const relative=latest?.[def.relative];return <button key={k} aria-pressed={metric===k} onClick={()=>setMetric(k)}><span>{def.label}</span><strong>{activityValue(value,def.unit)}</strong><small>{typeof relative==="number"?`${fmt(relative)}× relative`:"—"}</small></button>;})}</section>;
 const price=<section className="su-panel ma-price"><div className="su-panel-head"><h2>Price action</h2><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary ↗</Link></div><OverviewPriceChart points={rows} symbol={symbol} dark graphiteIce height={variant===5?180:variant===3?220:250}/></section>;
 const plot=<section className="su-panel ma-plot"><div className="su-panel-head"><h2>{view.title}</h2><span>{view.hardSpots} hard spot</span></div><MarketMetricChart points={view.points} unit={view.unit} title={view.title} height={variant===5?180:variant===3?200:variant===2?310:250} onSession={setSession}/></section>;
 const snapshot=<section className="su-panel ma-snapshot"><div className="su-panel-head"><h2>Activity pulse</h2><span>Relative</span></div><div className="ma-relative-grid">{(Object.keys(activityMetrics) as ActivityMetric[]).map(k=>{const v=latest?.[activityMetrics[k].relative];return <div key={k}><span>{activityMetrics[k].label}</span><strong>{typeof v==="number"?`${fmt(v)}×`:"—"}</strong></div>;})}</div><div className="ma-flow-line"><span>Foreign net / turnover</span><strong className={(data?.current.foreign_net_to_turnover??0)<0?"su-counter":"su-check"}>{data?.current.foreign_net_to_turnover==null?"—":`${fmt(data.current.foreign_net_to_turnover*100)}%`}</strong></div></section>;
 const sessionPanel=<section className="su-panel ma-session"><div className="su-panel-head"><h2>Session detail</h2><span>{focused?day(focused.date):"—"}</span></div><dl>{[["Close",activityValue(focused?.close,"idr")],["Volume",activityValue(focused?.volume,"shares")],["Turnover",activityValue(focused?.turnover_idr,"idr")],["Transactions",activityValue(focused?.transaction_count,"count")],["Average trade",activityValue(focused?.avg_trade_value_idr,"idr")],["Hard spot",focused?.spot_hit==null?"—":focused.spot_hit?"Detected":"Not detected"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>;
 const period=<section className="su-panel ma-period"><div className="su-panel-head"><h2>Period highlights</h2><span>{rows.length} sesi</span></div><div><span>Highest {view.title.toLowerCase()}</span><strong>{activityValue(view.peak?.value,view.unit)}</strong><small>{view.peak?day(view.peak.date):"—"}</small></div><div><span>Hard spot</span><strong>{rows.filter(p=>p.spot_hit===true).length}<em> sessions</em></strong></div><div><span>Price range</span><strong>{rows.some(p=>p.low!=null&&p.high!=null)?`${activityValue(Math.min(...rows.flatMap(p=>p.low==null?[]:[p.low])),"idr")} – ${activityValue(Math.max(...rows.flatMap(p=>p.high==null?[]:[p.high])),"idr")}`:"—"}</strong></div></section>;
 const sessions=<section className="su-panel ma-session-table"><div className="su-panel-head"><h2>Session explorer</h2><span>{view.title}</span></div><div className="ma-table-scroll"><table><thead><tr><th>Sesi</th><th>Close</th><th>{view.unit==="ratio"?"Relative":view.title}</th><th>Spot</th></tr></thead><tbody>{[...rows].reverse().map(p=>{const v=view.points.find(v=>v.date===p.date);return <tr key={p.date} className={focused?.date===p.date?"selected":""}><td><button onClick={()=>setSession(p.date)} aria-label={`Lihat sesi ${p.date}`}>{day(p.date)}</button></td><td>{fmt(p.close,0)}</td><td>{activityValue(v?.value,view.unit)}</td><td><span className={p.spot_hit?"su-check":"su-neutral"}>{p.spot_hit==null?"—":p.spot_hit?"□":"·"}</span></td></tr>;})}</tbody></table></div></section>;
 return <div className={`ov-demo ov-variant-4 su-demo ma-demo ma-variant-${variant}`}><div className="ov-reviewbar"><span>MARKET ACTIVITY CONCEPTS</span><div>{concepts.map((c,i)=><button key={c} aria-pressed={variant===i+1} onClick={()=>setParams({variant:String(i+1),symbol})}>{String(i+1).padStart(2,"0")} <span>{c}</span></button>)}</div></div><div className="ov-shell su-shell"><header className="ov-glass-nav"><NavbarGlass/><Link to="/design/overview?variant=4" className="ov-brand"><span className="ov-logo"><img src={`${import.meta.env.BASE_URL}signal-logo-generated.png`} alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/design/overview?variant=4">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><label className="su-stock-select"><span>Saham</span><select aria-label="Pilih saham" value={symbol} onChange={e=>setParams({variant:String(variant),symbol:e.target.value})}>{!stocks.length&&<option value={symbol}>{symbol}</option>}{stocks.map(s=><option value={s.symbol} key={s.symbol}>{s.symbol}</option>)}</select></label><WatchlistButton symbol={symbol} compact/><span className="ov-user">AS</span></header><main><div className="su-breadcrumb"><Link to="/investigations">Investigations</Link><span>/</span><span>{symbol}</span><span>/</span><strong>Market activity</strong></div><div className="su-stock-head"><div><h1>{symbol}</h1><span>{companyName(symbol,data?.identity.company_name)}</span></div><div className="su-stock-price"><span>Harga terakhir</span><strong>Rp {fmt(latest?.close,0)}</strong>{change!=null&&<small className={change<0?"su-counter":"su-check"}>{change>0?"+":""}{fmt(change)}%</small>}</div></div><nav className="su-tabs" aria-label="Navigasi investigasi"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary</Link><Link className="selected" to={`/design/activity?variant=${variant}&symbol=${symbol}`}>Market activity</Link><Link to={`/design/brokers?variant=1&symbol=${symbol}`}>Broker</Link><Link to={`/design/context?symbol=${symbol}`}>Context</Link><Link to={`/investigations/${symbol}/history`}>History</Link></nav>
 {error?<p role="alert" className="su-panel">{error}</p>:!data?<p role="status" className="su-panel">Memuat Market Activity…</p>:<>{controls}
 {variant===1&&<>{selector}<div className="ma-dual">{price}{plot}</div><div className="ma-bottom-three">{snapshot}{period}{sessionPanel}</div></>}
 {variant===2&&<div className="ma-activity-first"><div>{selector}{plot}<div className="ma-bottom-two">{period}{sessionPanel}</div></div><aside>{snapshot}{price}</aside></div>}
 {variant===3&&<>{selector}<div className="ma-dual-lens"><div>{price}{plot}</div><aside>{sessionPanel}{snapshot}{period}</aside></div></>}
 {variant===4&&<>{selector}<div className="ma-board-columns"><div>{plot}{price}</div><aside>{snapshot}{sessionPanel}{period}</aside></div></>}
 {variant===5&&<>{selector}<div className="ma-explorer"><div>{price}{plot}<div className="ma-bottom-two">{snapshot}{sessionPanel}</div></div>{sessions}</div></>}
 </>}
 </main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span><Link to={`/design/summary?variant=3&symbol=${symbol}`}>← Summary</Link></footer></div></div>;
}
