import {useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {getBrokerIndex,getBrokerSession,getBrokerEpisode,getBrokerHistory,getInvestigations} from '../lib/api';
import type {BrokerIndex,BrokerPayload,BrokerHistory,BrokerRow} from '../lib/brokerTypes';
import type {InvestigationListItem} from '../types';
import {filterBrokers,type BrokerSort} from '../lib/brokers';
import {companyName} from '../lib/companies';
import {activityValue} from '../lib/marketActivityView';
import {MarketMetricChart} from '../components/MarketMetricChart';
import '../overview-mockups.css';import '../summary-mockups.css';import '../activity-mockups.css';import '../broker-mockups.css';
const concepts=['Flow board','Broker desk','Evidence first','Compact terminal','Split explorer'];
const num=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('id-ID',{maximumFractionDigits:0});
const money=(v:number|null|undefined)=>activityValue(v,'idr');
const date=(d:string)=>new Date(d+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'});
const tone=(v:number|null)=>v==null?'':v<0?'su-counter':v>0?'su-check':'';
export function BrokerMockupsPage(){const [params,setParams]=useSearchParams();const raw=Number(params.get('variant')??1),variant=raw>=1&&raw<=5&&Number.isInteger(raw)?raw:1,symbol=(params.get('symbol')??'BBCA').toUpperCase();return <BrokerConcept key={symbol} symbol={symbol} variant={variant} navigate={(v,s)=>setParams({variant:String(v),symbol:s})}/>;}
function BrokerConcept({symbol,variant,navigate}:{symbol:string;variant:number;navigate:(v:number,s:string)=>void}){
 const [stocks,setStocks]=useState<InvestigationListItem[]>([]),[index,setIndex]=useState<BrokerIndex|null>(null),[data,setData]=useState<BrokerPayload|null>(null),[history,setHistory]=useState<BrokerHistory|null>(null);
 const [mode,setMode]=useState<'session'|'episode'>('session'),[day,setDay]=useState(''),[episode,setEpisode]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[historyError,setHistoryError]=useState('');
 const [query,setQuery]=useState(''),[side,setSide]=useState('ALL'),[sort,setSort]=useState<BrokerSort>('gross_value_idr'),[desc,setDesc]=useState(true),[expanded,setExpanded]=useState(false);
 useEffect(()=>{let alive=true;getInvestigations().then(d=>alive&&setStocks(d.items)).catch(()=>{});getBrokerIndex(symbol).then(d=>{if(alive){setIndex(d);setDay(d.default_date??d.dates.at(-1)??'');setEpisode(d.episodes.at(-1)?.investigation_id??'');}}).catch(()=>alive&&setError('Data broker belum dapat dimuat.'));return()=>{alive=false;};},[symbol]);
 useEffect(()=>{if(!index||!(mode==='session'?day:episode))return;let alive=true;setData(null);setHistory(null);setError('');(mode==='session'?getBrokerSession(symbol,day):getBrokerEpisode(symbol,episode)).then(d=>{if(alive){setData(d);setSelected([...d.brokers].sort((a,b)=>(b.gross_value_idr??-Infinity)-(a.gross_value_idr??-Infinity))[0]?.broker_code??'');}}).catch(()=>alive&&setError('Periode broker belum dapat dimuat.'));return()=>{alive=false;};},[symbol,index,mode,day,episode]);
 useEffect(()=>{let alive=true;setHistory(null);setHistoryError('');if(!data||!selected)return;if(mode==='episode'){setHistory(data.broker_histories?.find(h=>h.broker_code===selected)??null);return;}getBrokerHistory(symbol,selected,day).then(d=>alive&&setHistory(d)).catch(()=>alive&&setHistoryError('Riwayat broker belum dapat dimuat.'));return()=>{alive=false;};},[data,selected,symbol,day,mode]);
 const rows=useMemo(()=>filterBrokers(data?.brokers??[],query,side,sort,desc),[data,query,side,sort,desc]);const broker=data?.brokers.find(r=>r.broker_code===selected);
 const chart=useMemo(()=>history?.series.map(p=>({date:p.date,value:p.nval,hardSpot:false}))??[],[history]);
 const scope=mode==='session'?day?date(day):'—':data?.start&&data.last_observed_date?`${date(data.start)} — ${date(data.last_observed_date)}`:'—';
 const controls=<div className="br-scope"><div className="ma-windows" aria-label="Mode broker"><button aria-pressed={mode==='session'} onClick={()=>setMode('session')}>Per sesi</button><button aria-pressed={mode==='episode'} disabled={!index?.episodes.length} onClick={()=>setMode('episode')}>Per episode</button></div>{mode==='session'?<select aria-label="Tanggal sesi" value={day} onChange={e=>setDay(e.target.value)}>{[...(index?.dates??[])].reverse().map(d=><option key={d} value={d}>{date(d)}</option>)}</select>:<select aria-label="Episode broker" value={episode} onChange={e=>setEpisode(e.target.value)}>{index?.episodes.map(e=><option key={e.investigation_id} value={e.investigation_id}>{date(e.start)} — {date(e.last_observed_date)}</option>)}</select>}<span>{scope}</span></div>;
 const kpis=<section className="br-kpis">{[['Broker',data?num(data.brokers.length):'—'],['Total buy',data?.brokers.length?money(data.summary.totals.bval):'—'],['Total sell',data?.brokers.length?money(data.summary.totals.sval):'—'],['Top 5 buy share',data?.summary.top5_gross_buy_share_pct==null?'—':`${data.summary.top5_gross_buy_share_pct.toLocaleString('id-ID',{maximumFractionDigits:1})}%`]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</section>;
 function leader(title:string,codes:string[]){const max=Math.max(1,...codes.map(c=>Math.abs(data?.brokers.find(r=>r.broker_code===c)?.nval??0)));return <section className="su-panel br-leader"><div className="su-panel-head"><h2>{title}</h2><span>Top 5</span></div>{codes.map(c=>{const b=data?.brokers.find(r=>r.broker_code===c);return b?<button key={c} onClick={()=>setSelected(c)} className={selected===c?'selected':''}><strong>{c}</strong><span className="br-track"><i style={{width:`${Math.abs(b.nval??0)/max*100}%`,background:(b.nval??0)<0?'#ff8e9c':'#93c5fd'}}/></span><span className={tone(b.nval)}>{money(b.nval)}</span></button>:null;})}{!codes.length&&<p className="br-empty">—</p>}</section>;}
 const leaders=<div className="br-leaders">{leader('Net buy leaders',data?.summary.top5_net_buy_codes??[])}{leader('Net sell leaders',data?.summary.top5_net_sell_codes??[])}</div>;
 const table=<section className="su-panel br-table-panel"><div className="su-panel-head"><h2>All brokers</h2><span>{rows.length} / {data?.brokers.length??0}</span><button className="br-text-button" aria-pressed={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Compact columns':'Full columns'}</button></div><div className="br-filters"><input aria-label="Cari broker" placeholder="Cari kode / nama broker" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Arah net" value={side} onChange={e=>setSide(e.target.value)}><option value="ALL">Semua arah</option><option value="NET_BUY">Net buy</option><option value="NET_SELL">Net sell</option><option value="NET_FLAT">Net nol</option><option value="UNKNOWN">Unknown</option></select><select aria-label="Urutkan broker" value={sort} onChange={e=>setSort(e.target.value as BrokerSort)}><option value="gross_value_idr">Gross value</option><option value="bval">Buy value</option><option value="sval">Sell value</option><option value="nval">Net value</option><option value="broker_code">Broker code</option></select><button aria-label="Balik urutan" onClick={()=>setDesc(v=>!v)}>{desc?'↓':'↑'}</button></div><div className="br-table-scroll"><table><thead><tr><th>Broker</th><th>Buy</th><th>Sell</th><th>Net</th>{expanded&&<><th>Buy lot</th><th>Sell lot</th><th>Net lot</th><th>Buy freq</th><th>Sell freq</th></>}</tr></thead><tbody>{rows.map(b=><tr key={b.broker_code} className={selected===b.broker_code?'selected':''}><td><button aria-label={`Pilih broker ${b.broker_code}`} onClick={()=>setSelected(b.broker_code)}>{b.broker_code}</button><small>{b.broker_name??'—'}</small></td><td>{money(b.bval)}</td><td>{money(b.sval)}</td><td className={tone(b.nval)}>{money(b.nval)}</td>{expanded&&<><td>{num(b.blot)}</td><td>{num(b.slot)}</td><td>{num(b.nlot)}</td><td>{num(b.bfreq)}</td><td>{num(b.sfreq)}</td></>}</tr>)}</tbody></table></div>{!rows.length&&<p className="br-empty">{data?.brokers.length?'Tidak ada broker yang cocok.':'Data broker belum tersedia untuk periode ini.'}</p>}</section>;
 const detail=<section className="su-panel br-detail"><div className="su-panel-head"><h2>{selected||'Broker detail'}</h2><span className={tone(broker?.nval??null)}>{broker?.net_role==='NET_BUY'?'Net buy':broker?.net_role==='NET_SELL'?'Net sell':broker?.net_role==='NET_FLAT'?'Net nol':'—'}</span></div><p className="br-name">{broker?.broker_name??'—'}</p><div className="br-detail-metrics">{[['Buy',money(broker?.bval)],['Sell',money(broker?.sval)],['Net',money(broker?.nval)],['Buy / share',money(broker?.weighted_buy_price_per_share)],['Sell / share',money(broker?.weighted_sell_price_per_share)],['Buy share',broker?.buy_value_share_pct==null?'—':`${broker.buy_value_share_pct.toFixed(1)}%`]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>{historyError?<p role="alert">{historyError}</p>:history?<MarketMetricChart points={chart} unit="idr" title={`${selected} net flow`} signed height={variant===4?180:220}/>:<p className="br-empty">{selected?'Memuat riwayat…':'Pilih broker untuk melihat riwayat.'}</p>}</section>;
 return <div className={`ov-demo ov-variant-4 su-demo ma-demo br-demo br-variant-${variant}`}><div className="ov-reviewbar"><span>BROKER CONCEPTS</span><div>{concepts.map((c,i)=><button key={c} aria-pressed={variant===i+1} onClick={()=>navigate(i+1,symbol)}>{String(i+1).padStart(2,'0')} <span>{c}</span></button>)}</div></div><div className="ov-shell su-shell"><header className="ov-glass-nav"><Link className="ov-brand" to="/design/overview?variant=4"><span className="ov-logo"><img src={`${import.meta.env.BASE_URL}signal-logo-generated.png`} alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/design/overview?variant=4">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><label className="su-stock-select"><span>Saham</span><select aria-label="Pilih saham" value={symbol} onChange={e=>navigate(variant,e.target.value)}>{!stocks.length&&<option>{symbol}</option>}{stocks.map(s=><option key={s.symbol}>{s.symbol}</option>)}</select></label><span className="ov-user">AS</span></header><main><div className="su-breadcrumb"><Link to="/investigations">Investigations</Link><span>/</span><span>{symbol}</span><span>/</span><strong>Broker</strong></div><div className="su-stock-head"><div><h1>{symbol}</h1><span>{companyName(symbol)}</span></div><span className="br-heading-tag">Broker activity</span></div><nav className="su-tabs" aria-label="Navigasi investigasi"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary</Link><Link to={`/design/activity?variant=4&symbol=${symbol}`}>Market activity</Link><Link className="selected" to={`/design/brokers?variant=${variant}&symbol=${symbol}`}>Broker</Link><Link to={`/design/context?symbol=${symbol}`}>Context</Link><Link to={`/investigations/${symbol}/history`}>History</Link></nav>{controls}{error?<p role="alert" className="su-panel">{error}</p>:!data?<p role="status" className="su-panel">Memuat broker…</p>:<>{kpis}{variant===1&&<>{leaders}<div className="br-layout br-flow">{table}{detail}</div></>}{variant===2&&<div className="br-layout br-desk"><div>{table}</div><aside>{detail}{leaders}</aside></div>}{variant===3&&<><div className="br-evidence">{detail}{leaders}</div>{table}</>}{variant===4&&<><div className="br-compact-top">{leaders}{detail}</div>{table}</>}{variant===5&&<div className="br-layout br-split">{table}<aside>{detail}{leaders}</aside></div>}</>}</main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span><Link to={`/design/activity?variant=4&symbol=${symbol}`}>← Market activity</Link></footer></div></div>;
}
