import { WatchlistButton } from "../components/WatchlistButton";
import {useEffect,useState} from 'react';import {Link,useSearchParams} from '../lib/conceptNavigation';
import {getContext,getActivity,getInvestigations} from '../lib/api';import type {ContextPayload,ActivityPayload,InvestigationListItem} from '../types';
import {companyName,humanGroup} from '../lib/companies';import {activityValue} from '../lib/marketActivityView';import {OverviewPriceChart} from '../components/OverviewPriceChart';
import '../overview-mockups.css';import '../summary-mockups.css';import '../activity-mockups.css';import '../context-design.css';
const number=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('id-ID',{maximumFractionDigits:2});
const filters=['All','Company','Market','News'];
export function ContextDesignPage(){const [p,setP]=useSearchParams();const symbol=(p.get('symbol')??'BBCA').toUpperCase();return <ContextDesign key={symbol} symbol={symbol} choose={s=>setP({symbol:s})}/>;}
function ContextDesign({symbol,choose}:{symbol:string;choose:(s:string)=>void}){
 const [context,setContext]=useState<ContextPayload|null>(null),[activity,setActivity]=useState<ActivityPayload|null>(null),[stocks,setStocks]=useState<InvestigationListItem[]>([]),[filter,setFilter]=useState('All'),[error,setError]=useState('');
 useEffect(()=>{let alive=true;getInvestigations().then(d=>alive&&setStocks(d.items)).catch(()=>{});Promise.all([getContext(symbol),getActivity(symbol)]).then(([c,a])=>{if(alive){setContext(c);setActivity(a);}}).catch(()=>alive&&setError('Context belum dapat dimuat.'));return()=>{alive=false;};},[symbol]);
 const latest=activity?.series.at(-1),show=(x:string)=>filter==='All'||filter===x;
 const empty=(text:string)=><p className="ct-empty"><span>—</span>{text}</p>;
 const profile=<section className="su-panel ct-profile"><div className="su-panel-head"><h2>Company profile</h2><span>{symbol}</span></div><div className="ct-avatar">{symbol.slice(0,2)}</div><h3>{companyName(symbol,context?.identity.company_name)}</h3><dl><div><dt>Ticker</dt><dd>{symbol}</dd></div><div><dt>Group</dt><dd>{context?.identity.peer_group?humanGroup(context.identity.peer_group):'—'}</dd></div><div><dt>Market cap</dt><dd>{activityValue(latest?.market_cap,'idr')}</dd></div></dl>{context?.company_fundamentals?.available&&context.company_fundamentals.metrics.length>0&&<div className="ct-fundamentals">{context.company_fundamentals.metrics.map(m=><div key={m.label}><span>{m.label}</span><strong>{m.value}</strong></div>)}</div>}<div className="ct-quicklinks"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary ↗</Link><Link to={`/design/brokers/reference?symbol=${symbol}`}>Broker ↗</Link></div></section>;
 const price=<section className="su-panel ct-price"><div className="su-panel-head"><h2>Price context</h2><Link to={`/design/activity?variant=4&symbol=${symbol}`}>Market activity ↗</Link></div><OverviewPriceChart points={activity?.series??[]} symbol={symbol} dark graphiteIce height={240}/></section>;
 const market=<section className="su-panel"><div className="su-panel-head"><h2>Market context</h2></div>{context&&Object.keys(context.daily_market).length?<div className="ct-market-values">{[['Median activity',context.daily_market.market_activity_median],['Activity percentile',context.current.market_activity_percentile==null?null:context.current.market_activity_percentile*100],['Activity breadth',context.current.market_activity_breadth==null?null:context.current.market_activity_breadth*100]].map(([k,v])=><div key={String(k)}><span>{String(k)}</span><strong>{number(typeof v==='number'?v:null)}{v!=null&&k!=='Median activity'?'%':''}</strong></div>)}</div>:empty('Perbandingan pasar belum tersedia.')}</section>;
 const peers=<section className="su-panel ct-peers"><div className="su-panel-head"><h2>Peer comparison</h2></div>{context?.peer_comparison?.length?<div className="ct-table"><table><thead><tr><th>Stock</th><th>Activity</th><th>Rel. turnover</th><th>State</th></tr></thead><tbody>{context.peer_comparison.map(p=><tr key={p.symbol}><td><button onClick={()=>choose(p.symbol)}>{p.symbol}</button></td><td>{number(p.activity_score)}</td><td>{p.relative_turnover==null?'—':`${number(p.relative_turnover)}×`}</td><td>{p.state??'—'}</td></tr>)}</tbody></table></div>:empty('Perbandingan saham sekelompok belum tersedia.')}</section>;
 const events=<section className="su-panel ct-events"><div className="su-panel-head"><h2>Corporate events</h2><span>{context?.corporate_events?.length||'—'}</span></div>{context?.corporate_events?.length?<div className="ct-list">{context.corporate_events.map((e,i)=><article key={i}><time>{e.date}</time><strong>{e.type}</strong><p>{e.detail}</p></article>)}</div>:empty('Belum ada informasi corporate events.')}</section>;
 const news=<section className="su-panel ct-news"><div className="su-panel-head"><h2>Related news</h2><span>{context?.relevant_news?.length||'—'}</span></div>{context?.relevant_news?.length?<div className="ct-list">{context.relevant_news.map((n,i)=><article key={i}><time>{n.timestamp.slice(0,10)}</time><strong>{n.title??'—'}</strong><p>{n.source??''}{n.tags?.length?` · ${n.tags.join(' · ')}`:''}</p></article>)}</div>:empty('Berita terkait belum tersedia.')}</section>;
 return <div className="ov-demo ov-variant-4 su-demo ma-demo ct-demo"><div className="ov-reviewbar"><span>CONTEXT · GRAPHITE ICE</span></div><div className="ov-shell su-shell"><header className="ov-glass-nav"><Link className="ov-brand" to="/design/overview?variant=4"><span className="ov-logo"><img src="/signal-logo-generated.png" alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/design/overview?variant=4">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><label className="su-stock-select"><span>Saham</span><select aria-label="Pilih saham" value={symbol} onChange={e=>choose(e.target.value)}>{!stocks.length&&<option>{symbol}</option>}{stocks.map(s=><option key={s.symbol}>{s.symbol}</option>)}</select></label><WatchlistButton symbol={symbol} compact/><span className="ov-user">AS</span></header><main><div className="su-breadcrumb"><Link to="/investigations">Investigations</Link><span>/</span><span>{symbol}</span><span>/</span><strong>Context</strong></div><div className="su-stock-head"><div><h1>{symbol}</h1><span>{companyName(symbol)}</span></div><div className="su-stock-price"><span>Harga terakhir</span><strong>{activityValue(latest?.close,'idr')}</strong></div></div><nav className="su-tabs" aria-label="Navigasi investigasi"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary</Link><Link to={`/design/activity?variant=4&symbol=${symbol}`}>Market activity</Link><Link to={`/design/brokers/reference?symbol=${symbol}`}>Broker</Link><Link className="selected" to={`/design/context?symbol=${symbol}`}>Context</Link><Link to={`/investigations/${symbol}/history`}>History</Link></nav><div className="ct-toolbar"><div><span>Context</span><strong>The bigger picture.</strong></div><div className="ma-windows" aria-label="Filter context">{filters.map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>{error?<p role="alert" className="su-panel">{error}</p>:!context?<p role="status">Memuat Context…</p>:<>{show('Company')&&<div className="ct-top">{profile}{price}</div>}{show('Market')&&<div className="ct-middle">{market}{peers}</div>}<div className={`ct-bottom ${filter==='All'?'':'ct-single'}`}>{show('Company')&&events}{show('News')&&news}</div></>}</main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span><Link to={`/design/summary?variant=3&symbol=${symbol}`}>← Summary</Link></footer></div></div>;
}
