import {SnapshotFacts,ContextMarket,ContextPeers,ContextEvents,ContextNews} from '../components/ContextEnrichment';
import {NavbarGlass} from "../components/NavbarGlass";
import { WatchlistButton } from "../components/WatchlistButton";
import {useEffect,useState} from 'react';import {Link,useSearchParams} from '../lib/conceptNavigation';
import {getContext,getActivity,getInvestigations} from '../lib/api';import type {ContextPayload,ActivityPayload,InvestigationListItem} from '../types';
import {companyName,humanGroup} from '../lib/companies';import {activityValue} from '../lib/marketActivityView';import {OverviewPriceChart} from '../components/OverviewPriceChart';
import '../overview-mockups.css';import '../summary-mockups.css';import '../activity-mockups.css';import '../context-design.css';

const filters=['All','Company','Market','News'];
export function ContextDesignPage(){const [p,setP]=useSearchParams();const symbol=(p.get('symbol')??'BBCA').toUpperCase();return <ContextDesign key={symbol} symbol={symbol} choose={s=>setP({symbol:s})}/>;}
function ContextDesign({symbol,choose}:{symbol:string;choose:(s:string)=>void}){
 const [context,setContext]=useState<ContextPayload|null>(null),[activity,setActivity]=useState<ActivityPayload|null>(null),[stocks,setStocks]=useState<InvestigationListItem[]>([]),[filter,setFilter]=useState('All'),[error,setError]=useState('');
 useEffect(()=>{let alive=true;getInvestigations().then(d=>alive&&setStocks(d.items)).catch(()=>{});Promise.all([getContext(symbol),getActivity(symbol)]).then(([c,a])=>{if(alive){setContext(c);setActivity(a);}}).catch(()=>alive&&setError('Context belum dapat dimuat.'));return()=>{alive=false;};},[symbol]);
 const latest=activity?.series.at(-1),show=(x:string)=>filter==='All'||filter===x;

 const profile=<section className="su-panel ct-profile"><div className="su-panel-head"><h2>Company profile</h2><span>{symbol}</span></div><div className="ct-avatar">{symbol.slice(0,2)}</div><h3>{companyName(symbol,context?.identity.company_name)}</h3><dl><div><dt>Ticker</dt><dd>{symbol}</dd></div><div><dt>Group</dt><dd>{context?.identity.peer_group?humanGroup(context.identity.peer_group):'—'}</dd></div></dl><div className="ct-quicklinks"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary ↗</Link><Link to={`/design/brokers/reference?symbol=${symbol}`}>Broker ↗</Link></div></section>;
 const price=<section className="su-panel ct-price"><div className="su-panel-head"><h2>Price context</h2><Link to={`/design/activity?variant=4&symbol=${symbol}`}>Market activity ↗</Link></div><OverviewPriceChart points={activity?.series??[]} symbol={symbol} dark graphiteIce height={240}/></section>;
 const market=context&&<ContextMarket context={context}/>;
 const peers=context&&<ContextPeers context={context} choose={choose}/>;
 const events=context&&<ContextEvents context={context}/>;
 const news=context&&<ContextNews context={context}/>;
 return <div className="ov-demo ov-variant-4 su-demo ma-demo ct-demo"><div className="ov-reviewbar"><span>CONTEXT · GRAPHITE ICE</span></div><div className="ov-shell su-shell"><header className="ov-glass-nav"><NavbarGlass/><Link className="ov-brand" to="/design/overview?variant=4"><span className="ov-logo"><img src="/signal-logo-generated.png" alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/design/overview?variant=4">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><label className="su-stock-select"><span>Saham</span><select aria-label="Pilih saham" value={symbol} onChange={e=>choose(e.target.value)}>{!stocks.length&&<option>{symbol}</option>}{stocks.map(s=><option key={s.symbol}>{s.symbol}</option>)}</select></label><WatchlistButton symbol={symbol} compact/><span className="ov-user">AS</span></header><main><div className="su-breadcrumb"><Link to="/investigations">Investigations</Link><span>/</span><span>{symbol}</span><span>/</span><strong>Context</strong></div><div className="su-stock-head"><div><h1>{symbol}</h1><span>{companyName(symbol)}</span></div><div className="su-stock-price"><span>Harga terakhir</span><strong>{activityValue(latest?.close,'idr')}</strong></div></div><nav className="su-tabs" aria-label="Navigasi investigasi"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary</Link><Link to={`/design/activity?variant=4&symbol=${symbol}`}>Market activity</Link><Link to={`/design/brokers/reference?symbol=${symbol}`}>Broker</Link><Link className="selected" to={`/design/context?symbol=${symbol}`}>Context</Link><Link to={`/investigations/${symbol}/history`}>History</Link></nav><div className="ct-toolbar"><div><span>Context</span><strong>The bigger picture.</strong></div><div className="ma-windows" aria-label="Filter context">{filters.map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>{error?<p role="alert" className="su-panel">{error}</p>:!context?<p role="status">Memuat Context…</p>:<>{show('Company')&&<div className="ct-top">{profile}{price}</div>}{show('Company')&&context&&<section className="su-panel ct-snapshot-panel"><SnapshotFacts context={context}/></section>}{show('Market')&&<div className="ct-middle">{market}{peers}</div>}<div className={`ct-bottom ${filter==='All'?'':'ct-single'}`}>{show('Company')&&events}{show('News')&&news}</div></>}</main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span><Link to={`/design/summary?variant=3&symbol=${symbol}`}>← Summary</Link></footer></div></div>;
}
