import {NavbarGlass} from "../components/NavbarGlass";
import {useEffect,useState} from "react";
import {useParams,useNavigate} from "react-router-dom";
import {Link} from "../lib/conceptNavigation";
import {getActivity,getInvestigations} from "../lib/api";
import type {ActivityPayload,InvestigationListItem} from "../types";
import {WatchlistButton} from "../components/WatchlistButton";
import {companyName} from "../lib/companies";
import {activityValue} from "../lib/marketActivityView";
import {HistoryPage} from "./HistoryPage";
export function HistoryDesignPage(){const {symbol="BBCA"}=useParams();return <HistoryDesign key={symbol} symbol={symbol}/>;}
function HistoryDesign({symbol}:{symbol:string}){const nav=useNavigate(),choose=(s:string)=>nav("/investigations/"+s+"/history");const [stocks,setStocks]=useState<InvestigationListItem[]>([]),[activity,setActivity]=useState<ActivityPayload|null>(null);useEffect(()=>{let alive=true;getInvestigations().then(d=>alive&&setStocks(d.items)).catch(()=>{});getActivity(symbol).then(a=>alive&&setActivity(a)).catch(()=>{});return()=>{alive=false;};},[symbol]);const latest=activity?.series.at(-1);return <div className="ov-demo ov-variant-4 su-demo"><div className="ov-shell su-shell"><header className="ov-glass-nav"><NavbarGlass/><Link className="ov-brand" to="/design/overview?variant=4"><span className="ov-logo"><img src={`${import.meta.env.BASE_URL}signal-logo-generated.png`} alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/design/overview?variant=4">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><label className="su-stock-select"><span>Saham</span><select aria-label="Pilih saham" value={symbol} onChange={e=>choose(e.target.value)}>{!stocks.length&&<option>{symbol}</option>}{stocks.map(s=><option key={s.symbol}>{s.symbol}</option>)}</select></label><WatchlistButton symbol={symbol} compact/><span className="ov-user">AS</span></header><main><div className="su-breadcrumb"><Link to="/investigations">Investigations</Link><span>/</span><span>{symbol}</span><span>/</span><strong>History</strong></div><div className="su-stock-head"><div><h1>{symbol}</h1><span>{companyName(symbol)}</span></div><div className="su-stock-price"><span>Harga terakhir</span><strong>{activityValue(latest?.close,'idr')}</strong></div></div><nav className="su-tabs" aria-label="Navigasi investigasi"><Link to={`/design/summary?variant=3&symbol=${symbol}`}>Summary</Link><Link to={`/design/activity?variant=4&symbol=${symbol}`}>Market activity</Link><Link to={`/design/brokers/reference?symbol=${symbol}`}>Broker</Link><Link to={`/design/context?symbol=${symbol}`}>Context</Link><Link className="selected" to={`/investigations/${symbol}/history`}>History</Link></nav><HistoryPage/></main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span></footer></div></div>;}
