import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { getActivity, getHistory } from "../lib/api";
import type { ActivityPayload, ActivityPoint, HistoryPayload } from "../types";
import { CandlestickVolumeChart } from "../components/CandlestickVolumeChart";
import { SignalStrengthChart } from "../components/SignalStrengthChart";
import { StatusBadge } from "../components/StatusBadge";
import { formatNumber } from "../lib/format";
import { PilotQualityNotice } from "../components/PilotQualityNotice";
import { sessionFinding, qualityReason } from "../lib/pilot";

export function HistoryPage(){
  const {symbol=""}=useParams(); const [history,setHistory]=useState<HistoryPayload|null>(null); const [activity,setActivity]=useState<ActivityPayload|null>(null); const [selectedDate,setSelectedDate]=useState<string>(''); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let alive=true;Promise.all([getHistory(symbol),getActivity(symbol)]).then(([h,a])=>{if(alive){setHistory(h);setActivity(a);const rows=investigationSessions(a.series);setSelectedDate(rows.at(-1)?.date??a.series.at(-1)?.date??'')}}).catch((e:Error)=>alive&&setError(e.message));return()=>{alive=false;};},[symbol]);
  const [showAll,setShowAll]=useState(false);
  const sessions=useMemo(()=>activity?(showAll?activity.series:investigationSessions(activity.series)):[],[activity,showAll]); const selected=useMemo(()=>activity?.series.find(p=>p.date===selectedDate)??sessions.at(-1)??null,[activity,sessions,selectedDate]);
  if(error)return <div className="error-card workspace-page"><h2>Unable to load History</h2><p>{error}</p></div>;
  if(!history||!activity)return <div className="workspace-page"><div className="skeleton skeleton-card"/></div>;
  return <section className="workspace-page v23-history-page">
    <PilotQualityNotice data={activity}/>
    <div className="v23-history-heading"><h2>History</h2><p>Track how the investigation, signals, and supporting evidence have evolved over time.</p></div>
    <section className="v23-history-top"><article className="card v23-history-chart-card"><div className="v23-history-title"><span>▥</span><div><h3>Price & Investigation Timeline</h3><p>Stock price with key investigation sessions and trading volume.</p></div><span>Seluruh periode analisis</span></div><CandlestickVolumeChart points={activity.series} height={260}/></article><aside className="card v23-strength-card"><div className="v23-history-title"><span>⌁</span><div><h3>Signal Strength Over Time</h3><p>Evidence Confidence across active investigation sessions.</p></div></div><SignalStrengthChart points={activity.series} height={260}/></aside></section>
    <section className="v23-history-bottom"><article className="card v23-past-card"><div className="v23-history-title"><span>▣</span><div><h3>Past Investigations</h3><p>Historical sessions for {symbol.toUpperCase()}. Pilih semua sesi untuk meninjau data yang belum dapat dinilai.</p></div></div><label className="pilot-session-filter"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/> Tampilkan semua sesi, termasuk yang belum dapat dinilai</label><div className="v23-history-table-wrap"><table className="v23-history-table"><thead><tr><th>Date</th><th>Price (Close)</th><th>Daily Change</th><th>Signal Strength</th><th>Key Finding / Summary</th><th>Status</th><th/></tr></thead><tbody>{sessions.slice().reverse().map((p,i,rev)=>{const originalIndex=activity.series.findIndex(x=>x.date===p.date);const prev=originalIndex>0?activity.series[originalIndex-1].close:null;const ch=p.close!=null&&prev?((p.close-prev)/prev)*100:null;return <tr key={p.date} className={selectedDate===p.date?'selected':''} onClick={()=>setSelectedDate(p.date)}><td>{dateLabel(p.date)}</td><td>{p.close==null?'—':formatNumber(p.close,0)}</td><td className={ch==null?'':ch>=0?'pos':'neg'}>{ch==null?'—':`${ch>=0?'+':''}${formatNumber(ch,2)}%`}</td><td><Strength value={p.evidence_confidence}/></td><td>{sessionFinding(p)}</td><td><StatusBadge state={p.lifecycle_state}/></td><td>›</td></tr>})}</tbody></table></div></article><aside className="card v23-session-card"><div className="v23-history-title"><span>▣</span><div><h3>Session Detail</h3><p>Detailed point-in-time evidence for the selected session.</p></div></div>{selected?<SessionDetail point={selected}/>:<p>No selected session.</p>}</aside></section>
  </section>;
}
function investigationSessions(series:ActivityPoint[]){const active=new Set(['EMERGING','DEVELOPING','ESTABLISHED','WEAKENING','CLOSED']);return series.filter(p=>(p.lifecycle_state!=null&&active.has(p.lifecycle_state))||p.spot_hit===true)}
function Strength({value}:{value?:number|null}){const v=value??0;return <div className="v23-strength-cell"><span>{value==null?'—':formatNumber(value,0)}</span><i><b style={{width:`${Math.min(100,Math.max(0,v))}%`}}/></i></div>}

function SessionDetail({point}:{point:ActivityPoint}){const prevState=human(point.lifecycle_state);return <div className="v23-session-detail"><div className="v23-session-date"><span>{dateLabel(point.date)}</span><div><span>Price (Close)</span><strong>{point.close==null?'—':formatNumber(point.close,0)}</strong></div><div><span>Signal Strength</span><strong>{point.evidence_confidence==null?'—':`${formatNumber(point.evidence_confidence,0)}/100`}</strong><i><b style={{width:`${point.evidence_confidence??0}%`}}/></i></div></div><StatusBadge state={point.lifecycle_state}/><section><h4>Key Finding</h4><p>{sessionFinding(point)}</p></section><section><h4>Supporting Evidence</h4><ul><li>Turnover {point.relative_turnover==null?'—':`${formatNumber(point.relative_turnover,2)}x`} vs baseline</li><li>Transaction Count {point.relative_transaction_count==null?'—':`${formatNumber(point.relative_transaction_count,2)}x`} vs baseline</li><li>Avg Trade Value {point.relative_avg_trade_value==null?'—':`${formatNumber(point.relative_avg_trade_value,2)}x`} vs baseline</li><li>Activity Score {point.activity_score==null?'—':`${formatNumber(point.activity_score,1)}/100`}</li></ul></section><section><h4>Kualitas sesi</h4><p>{point.quality?.evaluation_status==='NOT_EVALUATED'?'Belum dapat dinilai':'Hasil deteksi sesi tersedia'}</p><ul>{point.quality?.reasons.map(reason=><li key={reason}>{qualityReason(reason)}</li>)}</ul></section><section><h4>Related Context</h4><ul><li>Lifecycle state: {prevState}</li><li>{point.spot_hit==null?'Spot belum dapat dinilai.':point.spot_hit?'Hard Spot hit on this session.':'No new hard Spot hit on this session.'}</li><li>{point.supporting_session==null?'Dukungan sesi belum dapat dinilai.':point.supporting_session?'Session supports the open investigation.':'Session does not support the open investigation.'}</li></ul></section></div>}
function dateLabel(v:string){const d=new Date(`${v}T00:00:00`);return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function human(v:string|null){if(v==null)return 'Belum dapat dinilai';return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
