import { useEffect, useMemo, useState } from "react";
import {isPilot, withLatestPrice} from "../lib/pilot";
import { useNavigate, useSearchParams } from "react-router-dom";
import { getActivity, getInvestigation, getInvestigations } from "../lib/api";
import type { ActivityPayload, InvestigationDetail, InvestigationExplorerPayload, InvestigationListItem } from "../types";
import { InvestigationTable } from "../components/InvestigationTable";
import { StatusBadge } from "../components/StatusBadge";
import { ConfidenceGauge } from "../components/ConfidenceGauge";
import { PdfAreaChart } from "../components/PdfAreaChart";
import { formatNumber } from "../lib/format";
import { companyName, humanGroup } from "../lib/companies";

export function InvestigationsPage(){
  const [params,setParams]=useSearchParams(); const navigate=useNavigate(); const [data,setData]=useState<InvestigationExplorerPayload|null>(null); const [detail,setDetail]=useState<InvestigationDetail|null>(null); const [activity,setActivity]=useState<ActivityPayload|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let alive=true;getInvestigations().then(async p=>{if(isPilot(p.methodology_version)){const items=await Promise.all(p.items.map(async item=>{const activity=await getActivity(item.symbol).catch(()=>null);return activity?withLatestPrice(item,activity):item;}));p={...p,items};}if(!alive)return;setData(p);if(!params.get('symbol')&&p.items.length){const first=[...p.items].sort((a,b)=>(b.evidence_confidence??-1)-(a.evidence_confidence??-1))[0];const n=new URLSearchParams(params);n.set('symbol',first.symbol);setParams(n,{replace:true})}}).catch((e:Error)=>alive&&setError(e.message));return()=>{alive=false;};},[]);
  const selected=params.get('symbol')??'';
  useEffect(()=>{setDetail(null);setActivity(null);if(!selected){return}let alive=true;Promise.all([getInvestigation(selected),getActivity(selected)]).then(([d,a])=>{if(alive){setDetail(d);setActivity(a)}}).catch(()=>{});return()=>{alive=false;};},[selected]);
  const filtered=useMemo(()=>{if(!data)return[];const q=(params.get('q')??'').toUpperCase();const state=params.get('state')??'';const group=params.get('group')??'';const conf=params.get('confidence')??'';const persistence=params.get('persistence')??'';return [...data.items].filter(x=>(!q||`${x.symbol} ${companyName(x.symbol,x.company_name)} ${x.peer_group??''}`.toUpperCase().includes(q))&&(!state||x.state===state)&&(!group||x.peer_group===group)&&(!conf||(conf==='70'?(x.evidence_confidence??0)>=70:conf==='50'?(x.evidence_confidence??0)>=50:(x.evidence_confidence??101)<50))&&(!persistence||(persistence==='4'?x.persistence_hits>=4:x.persistence_hits>=2))).sort((a,b)=>(b.evidence_confidence??-1)-(a.evidence_confidence??-1));},[data,params]);
  const groups=useMemo(()=>data?[...new Set(data.items.map(x=>x.peer_group).filter(Boolean) as string[])].sort():[],[data]);const states=useMemo(()=>data?[...new Set(data.items.map(x=>x.state))].sort():[],[data]);
  function setParam(k:string,v:string){const n=new URLSearchParams(params);v?n.set(k,v):n.delete(k);if(k!=='symbol')n.delete('symbol');setParams(n)} function select(item:InvestigationListItem){const n=new URLSearchParams(params);n.set('symbol',item.symbol);setParams(n)}
  if(error)return <div className="error-card"><h2>Unable to load investigations</h2><p>{error}</p></div>;
  return <section className="v23-investigations-page"><div className="v23-investigations-heading"><div><span>{data?.as_of??''}</span><h1>Saham dan status investigasi SIGNAL.</h1><p>Tinjau status snapshot setiap saham; status tanpa investigasi juga ditampilkan.</p></div></div><div className="card v23-filterbar"><label className="search"><span>⌕</span><input value={params.get('q')??''} onChange={e=>setParam('q',e.target.value)} placeholder="Search ticker or company..."/></label><Filter label="Pattern" value="sideways" disabled options={[['sideways','Sideways Accum.']]}/><Filter label="Sector" value={params.get('group')??''} onChange={v=>setParam('group',v)} options={groups.map(x=>[x,humanGroup(x)])}/><Filter label="State" value={params.get('state')??''} onChange={v=>setParam('state',v)} options={states.map(x=>[x,human(x)])}/><Filter label="Confidence" value={params.get('confidence')??''} onChange={v=>setParam('confidence',v)} options={[['70','70+'],['50','50+'],['under50','Under 50']]}/><Filter label="Persistence" value={params.get('persistence')??''} onChange={v=>setParam('persistence',v)} options={[['4','4/5 sessions'],['2','2/5+ sessions']]}/><button onClick={()=>setParams({})}>Reset</button></div><div className="v23-investigations-grid"><article className="card v23-investigations-table-card"><InvestigationTable items={filtered} selectedSymbol={selected} onSelect={select}/></article><aside className="card v23-quickview">{detail&&activity?<QuickPreview detail={detail} activity={activity} onOpen={()=>navigate(`/investigations/${detail.identity.symbol}/summary`)}/>:<div className="v23-empty"><h3>Select an investigation</h3></div>}</aside></div></section>
}
function QuickPreview({detail,activity,onOpen}:{detail:InvestigationDetail;activity:ActivityPayload;onOpen:()=>void}){const pts=activity.series.slice(-25).map(p=>({date:p.date,value:p.close}));const rows=activity.series.filter(p=>p.close!=null);const a=rows.at(-1)?.close,b=rows.at(-2)?.close;const ch=a!=null&&b?((a-b)/b)*100:null;return <><div className="v23-qv-top"><div><h2>{detail.identity.symbol}</h2><p>{companyName(detail.identity.symbol,detail.identity.company_name)}</p><span>{humanGroup(detail.identity.peer_group)}</span></div><div><strong>{detail.metrics.close==null?'—':formatNumber(detail.metrics.close,0)}</strong>{ch!=null&&<em className={ch>=0?'pos':'neg'}>{ch>=0?'+':''}{formatNumber(ch,2)}%</em>}</div></div><div className="v23-qv-state"><ConfidenceGauge value={detail.confidence.evidence_confidence} compact/><div><StatusBadge state={detail.state}/><strong>{detail.persistence.support_sessions_in_last_5}/5</strong><span>Persistence</span></div></div><div className="v23-qv-insight"><b>Key Insight</b><p>{detail.narrative_5w1h.what} {detail.narrative_5w1h.why}</p></div><div className="v23-qv-metrics"><div><span>Pattern</span><strong>{detail.hypothesis}</strong></div><div><span>Last Price</span><strong>{detail.metrics.close==null?'—':formatNumber(detail.metrics.close,0)}</strong></div><div><span>Sector</span><strong>{humanGroup(detail.identity.peer_group)}</strong></div><div><span>Market Context</span><strong>{human(detail.context.scope)}</strong></div></div><div className="v23-qv-chart"><PdfAreaChart points={pts} height={155} showBand={false}/></div><button className="v23-primary" onClick={onOpen}>Open Investigation →</button></>}
function Filter({label,value,onChange=()=>{},options,disabled=false}:{label:string;value:string;onChange?:(v:string)=>void;options:string[][];disabled?:boolean}){return <label><span>{label}</span><select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function human(v:string){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
