import {NavbarGlass} from "../components/NavbarGlass";
import { useEffect, useMemo, useRef, useState } from "react";
import {isPilot, withLatestPrice} from "../lib/pilot";
import { useNavigate, useSearchParams } from "react-router-dom";
import { getActivity, getInvestigation, getInvestigations } from "../lib/api";
import type { ActivityPayload, InvestigationDetail, InvestigationExplorerPayload, InvestigationListItem } from "../types";
import { StatusBadge } from "../components/StatusBadge";
import { ConfidenceGauge } from "../components/ConfidenceGauge";
import { OverviewPriceChart } from "../components/OverviewPriceChart";
import { Link } from "../lib/conceptNavigation";
import "../overview-mockups.css";
import "../summary-mockups.css";
import "../investigations-design.css";
import { formatNumber } from "../lib/format";
import { companyName, humanGroup } from "../lib/companies";

export function InvestigationsPage(){
  const [params,setParams]=useSearchParams(); const navigate=useNavigate(); const [data,setData]=useState<InvestigationExplorerPayload|null>(null); const [detail,setDetail]=useState<InvestigationDetail|null>(null); const [activity,setActivity]=useState<ActivityPayload|null>(null); const [error,setError]=useState<string|null>(null); const [previewError,setPreviewError]=useState(false);
  useEffect(()=>{let alive=true;getInvestigations().then(async p=>{if(isPilot(p.methodology_version)){const items=await Promise.all(p.items.map(async item=>{const activity=await getActivity(item.symbol).catch(()=>null);return activity?withLatestPrice(item,activity):item;}));p={...p,items};}if(!alive)return;setData(p);}).catch((e:Error)=>alive&&setError(e.message));return()=>{alive=false;};},[]);
  const previewRef=useRef<HTMLElement>(null),layoutRef=useRef<HTMLDivElement>(null);
  const selected=params.get('symbol')??'';
  useEffect(()=>{if(selected){previewRef.current?.scrollTo({top:0});layoutRef.current?.scrollIntoView({block:'nearest',behavior:'smooth'});}},[selected]);
  useEffect(()=>{setDetail(null);setActivity(null);setPreviewError(false);if(!selected){return}let alive=true;Promise.all([getInvestigation(selected),getActivity(selected)]).then(([d,a])=>{if(alive){setDetail(d);setActivity(a)}}).catch(()=>alive&&setPreviewError(true));return()=>{alive=false;};},[selected]);
  const filtered=useMemo(()=>{if(!data)return[];const q=(params.get('q')??'').toUpperCase();const state=params.get('state')??'';const group=params.get('group')??'';const conf=params.get('confidence')??'';const persistence=params.get('persistence')??'';return [...data.items].filter(x=>(!q||`${x.symbol} ${companyName(x.symbol,x.company_name)} ${x.peer_group??''}`.toUpperCase().includes(q))&&(!state||x.state===state)&&(!group||x.peer_group===group)&&(!conf||(conf==='70'?(x.evidence_confidence??0)>=70:conf==='50'?(x.evidence_confidence??0)>=50:(x.evidence_confidence??101)<50))&&(!persistence||(persistence==='4'?(x.persistence_hits ?? -1)>=4:(x.persistence_hits ?? -1)>=2))).sort((a,b)=>(b.evidence_confidence??-1)-(a.evidence_confidence??-1));},[data,params]);
  const groups=useMemo(()=>data?[...new Set(data.items.map(x=>x.peer_group).filter(Boolean) as string[])].sort():[],[data]);const states=useMemo(()=>data?[...new Set(data.items.map(x=>x.state))].sort():[],[data]);
  function setParam(k:string,v:string){const n=new URLSearchParams(params);v?n.set(k,v):n.delete(k);if(k!=='symbol')n.delete('symbol');setParams(n)} function select(item:InvestigationListItem){const n=new URLSearchParams(params);n.set('symbol',item.symbol);setParams(n)}
  return <div className="ov-demo ov-variant-4 su-demo ix-demo"><div className="ov-shell su-shell"><header className="ov-glass-nav"><NavbarGlass/><Link to="/" className="ov-brand"><span className="ov-logo"><img src={`${import.meta.env.BASE_URL}signal-logo-generated.png`} alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><span className="ov-user">AS</span></header><main><div className="ix-heading"><div><span className="ov-kicker">EXPLORE THE EVIDENCE</span><h1>Investigations</h1><p>Find a stock. Follow its story.</p></div><span>{filtered.length} {filtered.length===1?"stock":"stocks"}</span></div>
  <div className="ix-filterbar"><label className="ix-search"><span>Search</span><input aria-label="Cari saham atau perusahaan" value={params.get('q')??''} onChange={e=>setParam('q',e.target.value)} placeholder="Ticker or company…"/></label><Filter label="Sector" value={params.get('group')??''} onChange={v=>setParam('group',v)} options={groups.map(x=>[x,humanGroup(x)])}/><Filter label="State" value={params.get('state')??''} onChange={v=>setParam('state',v)} options={states.map(x=>[x,human(x)])}/><Filter label="Confidence" value={params.get('confidence')??''} onChange={v=>setParam('confidence',v)} options={[["70","70+"],["50","50+"],["under50","Under 50"]]}/><Filter label="Persistence" value={params.get('persistence')??''} onChange={v=>setParam('persistence',v)} options={[["4","4/5 sessions"],["2","2/5+ sessions"]]}/><button className="ix-reset" onClick={()=>setParams({})}>Reset</button></div>
  {error?<p className="su-panel" role="alert">{error}</p>:!data?<p className="su-panel" role="status">Memuat investigasi…</p>:<div ref={layoutRef} className={"ix-layout ix-split "+(selected?"has-preview":"")}><section className="ix-stock-panel" aria-label="Daftar saham"><div className="ix-results-head"><h2>All stocks</h2><span>Confidence · highest first</span></div><div className="ix-cards">{filtered.map(item=><article key={item.symbol} className={"ix-card "+(selected===item.symbol?"selected":"")}><div className="ix-card-top"><Link to={"/investigations/"+item.symbol+"/summary"}><span className="ov-stock-avatar">{item.symbol.slice(0,2)}</span><strong>{item.symbol}</strong></Link><StatusBadge state={item.state}/></div><p className="ix-company">{companyName(item.symbol,item.company_name)}</p><div className="ix-price"><strong>{item.close==null?"—":"Rp "+formatNumber(item.close,0)}</strong><span className={item.daily_change_pct==null?"":item.daily_change_pct>=0?"pos":"neg"}>{item.daily_change_pct==null?"—":(item.daily_change_pct>=0?"+":"")+formatNumber(item.daily_change_pct,2)+"%"}</span></div><div className="ix-metrics"><div><span>Confidence</span><strong>{item.evidence_confidence==null?"—":formatNumber(item.evidence_confidence,1)}<small>/100</small></strong></div><div><span>Rel. turnover</span><strong>{item.relative_turnover==null?"—":formatNumber(item.relative_turnover,2)+"×"}</strong></div><div><span>Persistence</span><strong>{item.persistence_hits==null?"—":item.persistence_hits+"/"+item.persistence_window}</strong></div></div><div className="ix-actions"><button aria-label={"Preview "+item.symbol} onClick={()=>select(item)}>Quick view</button><Link to={"/investigations/"+item.symbol+"/summary"}>Open investigation ↗</Link></div></article>)}</div>{!filtered.length&&<div className="su-panel ix-empty"><h3>No stocks match your search</h3><p>Adjust the filters or reset to explore all stocks.</p><button onClick={()=>setParams({})}>Reset filters</button></div>}</section>{selected?<aside ref={previewRef} className="ix-preview" aria-label="Quick view saham"><div className="ix-preview-head"><span>QUICK VIEW</span><button aria-label="Tutup quick view" onClick={()=>setParam('symbol','')}>×</button></div>{detail&&activity?<QuickPreview detail={detail} activity={activity} onOpen={()=>navigate('/investigations/'+detail.identity.symbol+'/summary')}/>:previewError?<p role="alert">Quick view belum dapat dimuat. Tutup lalu pilih saham kembali.</p>:<p role="status">Memuat {selected}…</p>}</aside>:<aside className="ix-preview ix-preview-empty" aria-label="Quick view saham"><span>QUICK VIEW</span><h2>A closer look.</h2><p>Pilih Quick view pada kartu saham untuk melihat ringkasan dan grafiknya di sini.</p></aside>}</div>}
  </main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span><Link to="/methodology">Methodology ↗</Link></footer></div></div>;
}
function QuickPreview({detail,activity,onOpen}:{detail:InvestigationDetail;activity:ActivityPayload;onOpen:()=>void}){const rows=activity.series.filter(p=>p.close!=null);const a=rows.at(-1)?.close,b=rows.at(-2)?.close;const ch=a!=null&&b?((a-b)/b)*100:null;return <><div className="v23-qv-top"><div><h2>{detail.identity.symbol}</h2><p>{companyName(detail.identity.symbol,detail.identity.company_name)}</p><span>{humanGroup(detail.identity.peer_group)}</span></div><div><strong>{detail.metrics.close==null?'—':formatNumber(detail.metrics.close,0)}</strong>{ch!=null&&<em className={ch>=0?'pos':'neg'}>{ch>=0?'+':''}{formatNumber(ch,2)}%</em>}</div></div><div className="v23-qv-state"><ConfidenceGauge value={detail.confidence.evidence_confidence} compact/><div><StatusBadge state={detail.state}/><strong>{formatNumber(detail.persistence.support_sessions_in_last_5,0)}/5</strong><span>Persistence</span></div></div><div className="v23-qv-insight"><b>Key Insight</b><p>{detail.narrative_5w1h.what} {detail.narrative_5w1h.why}</p></div><div className="v23-qv-metrics"><div><span>Pattern</span><strong>{detail.hypothesis}</strong></div><div><span>Last Price</span><strong>{detail.metrics.close==null?'—':formatNumber(detail.metrics.close,0)}</strong></div><div><span>Sector</span><strong>{humanGroup(detail.identity.peer_group)}</strong></div><div><span>Market Context</span><strong>{human(detail.context.scope)}</strong></div></div><div className="v23-qv-chart"><OverviewPriceChart points={activity.series} symbol={detail.identity.symbol} height={210} dark graphiteIce/></div><button className="v23-primary" onClick={onOpen}>Open Investigation →</button></>}
function Filter({label,value,onChange=()=>{},options,disabled=false}:{label:string;value:string;onChange?:(v:string)=>void;options:string[][];disabled?:boolean}){return <label><span>{label}</span><select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}><option value="">All</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function human(v:string){return v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
