import {NavbarGlass} from "../components/NavbarGlass";
import { WatchlistButton } from "../components/WatchlistButton";
import { useEffect, useState } from "react";
import { Link, useSearchParams } from "../lib/conceptNavigation";
import { getActivity, getHistory, getInvestigations, getSummary } from "../lib/api";
import type { ActivityPayload, HistoryPayload, InvestigationListItem, SummaryPayload } from "../types";
import { OverviewPriceChart } from "../components/OverviewPriceChart";
import { companyName } from "../lib/companies";
import "../overview-mockups.css";
import "../summary-mockups.css";

const concepts = ["Balanced", "Research desk", "Evidence first", "Compact board", "Terminal"];
const fmt = (v:number|null|undefined,d=1)=>v==null ? "—" : v.toLocaleString("id-ID",{maximumFractionDigits:d});
const day = (v:string|null)=>v ? new Date(v+"T00:00:00").toLocaleDateString("id-ID",{day:"numeric",month:"short"}) : "—";
const states:Record<string,string> = {EMERGING:"Emerging",DEVELOPING:"Developing",ESTABLISHED:"Established",WEAKENING:"Weakening",CLOSED:"Selesai",UNKNOWN:"Belum diketahui",NO_INVESTIGATION:"Tidak aktif",INELIGIBLE_PRICE_REGIME:"Tidak memenuhi kondisi harga"};
const eventLabels:Record<string,string> = {INVESTIGATION_OPENED:"Investigasi dibuka",INVESTIGATION_CLOSED:"Investigasi selesai",STATE_CHANGE:"Perubahan status",SPOT_HIT:"Hard spot"};
const evidenceValue=(e:SummaryPayload["investigation"]["supporting_evidence"][number])=>e.relative!=null ? (e.metric.includes("foreign") ? `${fmt(e.relative*100,2)}%` : `${fmt(e.relative,2)}×`) : e.score!=null ? `${fmt(e.score)}/100` : fmt(e.value,2);
const conditionLabel:Record<string,string> = {continuation_compression:"Kompresi harga tetap mendukung",continuation_activity:"Aktivitas perdagangan tetap mendukung",established_support:"Dukungan minimal 4 dari 5 sesi",established_hard_hits:"Minimal 2 hard spot dalam episode",closure_watch:"Tidak ada 2 sesi tanpa dukungan beruntun"};
export function SummaryMockupsPage(){
 const [params,setParams]=useSearchParams();const n=Number(params.get("variant")??3);const variant=Number.isInteger(n)&&n>=1&&n<=5?n:1;const symbol=(params.get("symbol")??"BBCA").toUpperCase();
 const [data,setData]=useState<SummaryPayload>();const [activity,setActivity]=useState<ActivityPayload>();const [history,setHistory]=useState<HistoryPayload>();const [stocks,setStocks]=useState<InvestigationListItem[]>([]);const [error,setError]=useState("");const [secondaryError,setSecondaryError]=useState(false);
 useEffect(()=>{let alive=true;getInvestigations().then(d=>alive&&setStocks(d.items)).catch(()=>{});return()=>{alive=false;};},[]);
 useEffect(()=>{let alive=true;setData(undefined);setActivity(undefined);setHistory(undefined);setError("");setSecondaryError(false);Promise.all([getSummary(symbol),Promise.allSettled([getActivity(symbol),getHistory(symbol)])]).then(([d,extra])=>{if(!alive)return;setData(d);if(extra[0].status==="fulfilled")setActivity(extra[0].value as ActivityPayload);if(extra[1].status==="fulfilled")setHistory(extra[1].value as HistoryPayload);setSecondaryError(extra.some(v=>v.status==="rejected"));}).catch(()=>alive&&setError("Summary belum dapat dimuat. Pilih saham lain atau periksa server lokal."));return()=>{alive=false;};},[symbol]);
 const changeVariant=(v:number)=>setParams({variant:String(v),symbol});
 const inv=data?.investigation;const price=inv?.metrics.close;const valid=activity?.series.filter(p=>p.close!=null)??[];const previous=valid.at(-2)?.close;const change=price!=null&&previous!=null&&previous!==0?(price-previous)/previous*100:null;
 const metrics=inv ? [{label:"Evidence confidence",value:fmt(inv.confidence.evidence_confidence),unit:"/100"},{label:"Range 5 sesi",value:fmt(inv.metrics.current_5d_range_pct,2),unit:"%"},{label:"Relative turnover",value:fmt(inv.metrics.relative_turnover,2),unit:"×"},{label:"Dukungan 5 sesi",value:fmt(inv.persistence.support_sessions_in_last_5,0),unit:"/5"},{label:"Hard spot episode",value:fmt(inv.persistence.hard_hits_total_in_episode,0),unit:"hit"}] : [];
 const metricStrip=<section className="su-metric-strip" aria-label="Metrik investigasi">{metrics.map(m=><div key={m.label}><span>{m.label}</span><strong>{m.value}{m.value!=="—"&&<em>{m.unit}</em>}</strong></div>)}</section>;
 const insight=inv ? <section className="su-panel su-insight"><div className="su-panel-head"><h2>Investigation brief</h2><span className="su-label">{states[inv.state]??inv.state}</span></div><h3>{inv.hypothesis}</h3><p>{inv.active===true ? "Investigasi sedang berlangsung. Perhatikan keseimbangan bukti pendukung, bukti berlawanan, dan kelanjutan aktivitasnya." : inv.active===false ? "Tidak ada investigasi aktif. Jelajahi histori untuk melihat episode yang telah terbentuk." : "Status investigasi belum diketahui."}</p><div className="su-facts"><span>Dibuka <strong>{day(inv.opened_at)}</strong></span><span>Durasi <strong>{fmt(inv.age_sessions,0)}{inv.age_sessions==null?"":" sesi"}</strong></span><span>Monitoring <strong>{inv.active==null?"—":inv.active?"Aktif":"Tidak aktif"}</strong></span></div><div className="su-quicklinks"><Link to={`/investigations/${symbol}/activity`}>Market activity ↗</Link><Link to={`/design/brokers?variant=1&symbol=${symbol}`}>Broker ↗</Link></div></section> : null;
 const chart=<section className="su-panel su-chart-panel"><div className="su-panel-head"><h2>Price action</h2><span>IDR</span></div>{activity?<OverviewPriceChart points={activity.series} symbol={symbol} dark graphiteIce height={variant===2?270:variant===5?240:250}/>:<p className="su-empty">Grafik harga belum tersedia.</p>}</section>;
 const evidence=inv ? <section className="su-panel su-evidence"><div className="su-panel-head"><h2>Evidence</h2><Link to={`/investigations/${symbol}/activity`}>Lihat detail ↗</Link></div><div className="su-evidence-columns"><div><h3><span className="su-check">+</span> Mendukung <small>{inv.supporting_evidence.length}</small></h3>{inv.supporting_evidence.map(e=><div className="su-evidence-row" key={e.evidence_id}><span>{e.label}</span><strong>{evidenceValue(e)}</strong></div>)}{!inv.supporting_evidence.length&&<p className="su-empty">Belum ada bukti pendukung.</p>}</div><div><h3><span className="su-counter">−</span> Berlawanan <small>{inv.contradicting_evidence.length}</small></h3>{inv.contradicting_evidence.map(e=><div className="su-evidence-row" key={e.evidence_id}><span>{e.label}</span><strong>{evidenceValue(e)}</strong></div>)}{!inv.contradicting_evidence.length&&<p className="su-empty">Tidak ada bukti berlawanan yang tercatat.</p>}</div></div></section> : null;
 const conditions=inv ? <section className="su-panel su-conditions"><div className="su-panel-head"><h2>What to watch</h2><span>Continuation</span></div>{inv.look_ahead.map(c=><div className="su-condition" key={c.condition_id}><span className={c.current_status==="MET"?"su-check":"su-neutral"} aria-hidden="true">{c.current_status==="MET"?"✓":c.current_status==="NOT_MET"?"○":"—"}</span><span>{conditionLabel[c.condition_id]??c.label}</span><small>{c.current_status==="MET"?"Terpenuhi":c.current_status==="NOT_MET"?"Belum":"—"}</small></div>)}</section> : null;
 const events=history?.events.filter(e=>e.investigation_id && e.investigation_id===inv?.investigation_id).slice(-5).reverse()??[];
 const timeline=<section className="su-panel su-timeline"><div className="su-panel-head"><h2>Episode timeline</h2><Link to={`/investigations/${symbol}/history`}>History ↗</Link></div>{events.map((e,i)=><div className="su-event" key={`${e.date}-${e.event_type}-${i}`}><span className="su-event-dot"/><time>{day(e.date)}</time><span>{eventLabels[e.event_type]??e.event_type}</span><small>{states[e.state]??e.state}</small></div>)}{!events.length&&<p className="su-empty">{history?"Tidak ada episode aktif. Lihat histori investigasi.":"Histori belum tersedia."}</p>}</section>;
 const participation=inv ? <section className="su-panel su-participation"><div className="su-panel-head"><h2>Participation</h2><Link to={`/design/brokers?variant=1&symbol=${symbol}`}>Broker ↗</Link></div><div className="su-participation-grid"><div><span>Relative volume</span><strong>{fmt(inv.metrics.relative_volume,2)}{inv.metrics.relative_volume==null?"":"×"}</strong></div><div><span>Relative transactions</span><strong>{fmt(inv.metrics.relative_transaction_count,2)}{inv.metrics.relative_transaction_count==null?"":"×"}</strong></div><div><span>Foreign net / turnover</span><strong className={(inv.metrics.foreign_net_to_turnover??0)<0?"su-counter":""}>{inv.metrics.foreign_net_to_turnover==null?"—":`${fmt(inv.metrics.foreign_net_to_turnover*100,2)}%`}</strong></div><div><span>Context specificity</span><strong>{fmt(inv.context.specificity_score,0)}{inv.context.specificity_score==null?"":"/100"}</strong></div></div></section> : null;
 return <div className={`ov-demo ov-variant-4 su-demo su-variant-${variant}`}><div className="ov-reviewbar"><span>SUMMARY CONCEPTS</span><div>{concepts.map((c,i)=><button key={c} aria-pressed={variant===i+1} onClick={()=>changeVariant(i+1)}>{String(i+1).padStart(2,"0")} <span>{c}</span></button>)}</div></div><div className="ov-shell su-shell"><header className="ov-glass-nav"><NavbarGlass/><Link to="/design/overview?variant=4" className="ov-brand"><span className="ov-logo"><img src="/signal-logo-generated.png" alt=""/></span>SIGNAL</Link><nav aria-label="Navigasi utama"><Link to="/design/overview?variant=4">Overview</Link><Link className="selected" to="/investigations">Investigations</Link><Link to="/watchlist">Watchlist</Link><Link to="/methodology">Methodology</Link></nav><label className="su-stock-select"><span>Saham</span><select aria-label="Pilih saham" value={symbol} onChange={e=>setParams({variant:String(variant),symbol:e.target.value})}>{!stocks.length&&<option value={symbol}>{symbol}</option>}{stocks.map(s=><option value={s.symbol} key={s.symbol}>{s.symbol}</option>)}</select></label><span className="ov-user" aria-label="Profil Aldo">AS</span></header><main>
 <div className="su-breadcrumb"><Link to="/investigations">Investigations</Link><span>/</span><span>{symbol}</span><span>/</span><strong>Summary</strong></div>
 <div className="su-stock-head"><div><h1>{symbol}</h1><span>{companyName(symbol,inv?.identity.company_name)}</span>{inv&&<span className="su-label">{states[inv.state]??inv.state}</span>}</div><div className="su-stock-price"><span>Harga terakhir</span><strong>Rp {fmt(price,0)}</strong>{change!=null&&<small className={change<0?"su-counter":"su-check"}>{change>0?"+":""}{fmt(change,2)}%</small>}</div></div>
 <nav className="su-tabs" aria-label="Navigasi investigasi"><Link className="selected" to={`/design/summary?variant=${variant}&symbol=${symbol}`}>Summary</Link><Link to={`/design/activity?variant=1&symbol=${symbol}`}>Market activity</Link><Link to={`/design/brokers?variant=1&symbol=${symbol}`}>Broker</Link><Link to={`/design/context?symbol=${symbol}`}>Context</Link><Link to={`/investigations/${symbol}/history`}>History</Link></nav>
 {error?<p role="alert" className="su-panel">{error}</p>:!inv?<p role="status" className="su-panel">Memuat Summary…</p>:<>{secondaryError&&<p className="su-empty" role="alert">Sebagian panel belum dapat dimuat.</p>}
 {variant===1&&<>{metricStrip}<div className="su-balanced-top">{chart}{insight}</div><div className="su-balanced-bottom">{evidence}{conditions}</div><div className="su-two-col">{participation}{timeline}</div></>}
 {variant===2&&<><div className="su-desk"><aside>{insight}{timeline}</aside><div className="su-desk-center">{chart}{metricStrip}</div><aside>{evidence}{conditions}</aside></div>{participation}</>}
 {variant===3&&<>{metricStrip}<div className="su-evidence-first">{evidence}{chart}</div><div className="su-three-col">{insight}{conditions}{timeline}</div>{participation}</>}
 {variant===4&&<><div className="su-board"><div className="su-board-main">{chart}{metricStrip}</div><aside>{insight}{participation}</aside></div><div className="su-board-bottom">{evidence}<div>{conditions}{timeline}</div></div></>}
 {variant===5&&<>{metricStrip}<div className="su-terminal"><div>{chart}{insight}<div className="su-two-col">{participation}{timeline}</div></div><aside>{evidence}{conditions}</aside></div></>}
 </>}
 </main><footer className="su-footer"><strong>SIGNAL</strong><span>Look closer. Think clearer.</span><Link to="/design/overview?variant=4">← Overview</Link></footer></div></div>;
}
